name: Deploy UgandaEMR to Server

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Build and push Docker image to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        id: docker
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/ugandaemr-distro
          IMAGE_TAG=$(git rev-parse --short HEAD)

          # Build image without cache
          docker build --no-cache -t "$IMAGE_NAME:$IMAGE_TAG" .

          # Tag the latest version
          docker tag "$IMAGE_NAME:$IMAGE_TAG" "$IMAGE_NAME:latest"

          # Push both tagged and latest versions
          docker push "$IMAGE_NAME:$IMAGE_TAG"
          docker push "$IMAGE_NAME:latest"

          # Output the tag for the next steps
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      # Step 3: Set up SSH key for secure communication
      - name: Set up SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: |
            ${{ secrets.SERVER_IP }}

      # Step 4: Sync docker-compose.yml to the server
      - name: Sync docker-compose.yml to Server
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" docker-compose.yml "${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:/home/ugandaemr"

      # Step 5: SSH into the server, pull the latest image, and restart services
      - name: Update and Restart Services on Server
        run: |
          ssh -o StrictHostKeyChecking=no "${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}" << 'EOF'
            cd /home/ugandaemr
            docker-compose pull
            docker-compose up -d
          EOF
