name: Deploy UgandaEMR to server

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Build and push Docker image to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build --no-cache -t ${{secrets.DOCKER_USERNAME}}/ugandaemr-distro:$(git rev-parse --short HEAD) .
          docker tag ${{secrets.DOCKER_USERNAME}}/ugandaemr-distro:$(git rev-parse --short HEAD) ${{secrets.DOCKER_USERNAME}}/ugandaemr-distro
          docker push ${{secrets.DOCKER_USERNAME}}/ugandaemr-distro:$(git rev-parse --short HEAD)
          docker push ${{secrets.DOCKER_USERNAME}}/ugandaemr-distro:latest

      # Step 3: Sync docker-compose file to the server
      - name: Sync docker-compose.yml to server
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" docker-compose.yml ${{secrets.USER}}@${{ secrets.SERVER_IP }}:/home/ugandaemr


      # Step 4: SSH into server, pull latest image, and restart services
      - name: Update and restart services on the server
        run: |
          ssh -o StrictHostKeyChecking=no ${{secrets.USER}}@${{ secrets.SERVER_IP }} << 'EOF'
            cd /home/ugandaemr
            docker-compose pull
            docker-compose up -d
          EOF
        env:
          DOCKER_HOST: "ssh://${{secrets.USER}}@${{ secrets.SERVER_IP }}"
