name: Deploy UgandaEMR to Server

on:
  workflow_run:
    workflows: ["Build and Push UgandaEMR Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Set up SSH Key for secure communication
      - name: Set up SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      # Step 2: Sync docker-compose.yml to the server
      - name: Sync docker-compose.yml to Server
        run: |
          rsync -avz -e ssh docker-compose.yml "${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:/home/ugandaemr"

      # Step 3: SSH into the server, pull the latest image, and restart services
      - name: Update and Restart Services on Server
        run: |
          ssh "${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}" << 'EOF'
            cd /home/ugandaemr
            docker-compose pull
            docker-compose up -d
          EOF
